"""change relationship

Revision ID: 08622ffba9e9
Revises: 93f3023a11ea
Create Date: 2021-12-11 17:42:50.743985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08622ffba9e9'
down_revision = '93f3023a11ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
