"""change date to datatype in price model

Revision ID: 17fb2255f9af
Revises: db26ad2ea156
Create Date: 2021-12-18 20:23:59.251485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fb2255f9af'
down_revision = 'db26ad2ea156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
