"""add url in product

Revision ID: 72a520930326
Revises: eba1ec71007c
Create Date: 2021-12-07 20:29:06.787120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a520930326'
down_revision = 'eba1ec71007c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'url')
    # ### end Alembic commands ###
