"""remove name and phone from User

Revision ID: 8c9b03e3a7ac
Revises: 17fb2255f9af
Create Date: 2021-12-26 23:33:05.045833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9b03e3a7ac'
down_revision = '17fb2255f9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
