"""add price_is_ps_plus in price

Revision ID: 93f3023a11ea
Revises: 72a520930326
Create Date: 2021-12-10 20:52:23.376659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f3023a11ea'
down_revision = '72a520930326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('price_is_ps_plus', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'price_is_ps_plus')
    # ### end Alembic commands ###
