"""change price datatype

Revision ID: e9376820127c
Revises: 08622ffba9e9
Create Date: 2021-12-12 21:04:04.603856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9376820127c'
down_revision = '08622ffba9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
