"""add classmetod

Revision ID: eba1ec71007c
Revises: a53e2c484d7f
Create Date: 2021-12-05 17:47:40.465578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba1ec71007c'
down_revision = 'a53e2c484d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
